"""Command-line entry point: ``python -m nse_monitor <command>``."""
from __future__ import annotations

import argparse
import logging
import sys
from datetime import date
from logging.handlers import RotatingFileHandler

import pandas as pd

from .config import AppConfig, load_config
from .data import create_source
from .engine import Engine
from .notifications import build_notifiers, dispatch_pending, fmt_date
from .reports import HISTORY_DISPLAY_LIMIT, active_table, crossover_stats, export_reports, history_table
from .storage import Repository


def _setup_logging(cfg: AppConfig, verbose: bool) -> None:
    log_dir = cfg.path(cfg.log_dir)
    log_dir.mkdir(parents=True, exist_ok=True)
    fmt = logging.Formatter("%(asctime)s %(levelname)-7s %(name)s: %(message)s")
    file_handler = RotatingFileHandler(log_dir / "nse_monitor.log", maxBytes=5_000_000, backupCount=5,
                                       encoding="utf-8")
    file_handler.setFormatter(fmt)
    console = logging.StreamHandler()
    console.setFormatter(fmt)
    console.setLevel(logging.DEBUG if verbose else logging.INFO)
    root = logging.getLogger()
    root.setLevel(logging.DEBUG if verbose else logging.INFO)
    root.handlers[:] = [file_handler, console]
    for noisy in ("yfinance", "urllib3", "peewee"):
        logging.getLogger(noisy).setLevel(logging.WARNING)


def _print_df(df: pd.DataFrame, empty: str) -> None:
    if df.empty:
        print(empty)
    else:
        with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.width", 250):
            print(df.to_string(index=False))


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")  # ₹ on Windows consoles
        except Exception:
            pass

    p = argparse.ArgumentParser(prog="nse_monitor", description="NSE RSI<30 -> SMA50 crossover monitor")
    p.add_argument("--config", help="path to config.toml (default: ./config.toml if present)")
    p.add_argument("--db", help="override database path")
    p.add_argument("-v", "--verbose", action="store_true")
    sub = p.add_subparsers(dest="cmd", required=True)

    r = sub.add_parser("run", help="daily job: process all unprocessed trading days, alert, export")
    r.add_argument("--as-of", type=date.fromisoformat, help="treat this date (YYYY-MM-DD) as today")
    r.add_argument("--no-notify", action="store_true", help="queue alerts but do not send them")

    rp = sub.add_parser("replay", help="backfill/simulate from a past date (use a fresh --db)")
    rp.add_argument("--start", type=date.fromisoformat, required=True)
    rp.add_argument("--end", type=date.fromisoformat)
    rp.add_argument("--notify", action="store_true", help="also send the alerts generated by the replay")

    sub.add_parser("status", help="show the active tracking list")
    hp = sub.add_parser("history", help="show the historical crossover database (latest exits first) and statistics")
    hp.add_argument("--limit", type=int, default=HISTORY_DISPLAY_LIMIT,
                    help=f"rows to show (default {HISTORY_DISPLAY_LIMIT}; 0 = all)")
    a = sub.add_parser("audit", help="show the audit log")
    a.add_argument("--symbol")
    a.add_argument("--limit", type=int, default=50)
    sub.add_parser("export", help="write CSV + HTML reports")
    sub.add_parser("notify-test", help="send a test message on every configured channel")
    sub.add_parser("retry-alerts", help="re-send alerts that failed to deliver")

    args = p.parse_args(argv)
    cfg = load_config(args.config)
    if args.db:
        cfg.db_path = args.db
    _setup_logging(cfg, args.verbose)
    repo = Repository(cfg.path(cfg.db_path))
    notifiers = build_notifiers(cfg.notify)

    try:
        if args.cmd in ("run", "replay"):
            engine = Engine(cfg, repo, create_source(cfg), notifiers)
            if args.cmd == "run":
                res = engine.run(as_of=args.as_of, notify=not args.no_notify)
            else:
                res = engine.run(as_of=args.end, start=args.start, notify=args.notify)
                if not args.notify:  # historical alerts must not be sent by the next daily run
                    repo.suppress_pending_alerts("suppressed: generated by replay")
            crossed = [e.symbol for e in res.events if e.kind == "CROSSED"]
            entered = [e.symbol for e in res.events if e.kind == "ENTERED"]
            print(f"Processed {len(res.processed_days)} trading day(s)"
                  + (f" [{fmt_date(res.processed_days[0])} .. {fmt_date(res.processed_days[-1])}]"
                     if res.processed_days else ""))
            print(f"New RSI<30 entries: {len(entered)} | SMA50 crossovers: {len(crossed)} | "
                  f"Active now: {len(repo.active())} | alerts sent {res.alerts_sent}, failed {res.alerts_failed}")
            if res.skipped_reason:
                print(res.skipped_reason)
        elif args.cmd == "status":
            print(f"Active tracking list (last processed: {fmt_date(repo.last_processed_day())})")
            _print_df(active_table(repo), "No stocks are being tracked.")
        elif args.cmd == "history":
            hist = history_table(repo)
            _print_df(hist.head(args.limit) if args.limit else hist, "No completed records yet.")
            if args.limit and len(hist) > args.limit:
                print(f"\n(showing latest {args.limit} of {len(hist)}; use --limit 0 for all)")
            s = crossover_stats(repo)
            if s.get("count"):
                print(f"\nCrossovers: {s['count']} | trading days to cross: mean {s['mean']}, "
                      f"median {s['median']}, min {s['min']}, max {s['max']}")
        elif args.cmd == "audit":
            _print_df(pd.DataFrame(repo.audit_log(args.symbol, args.limit)), "Audit log is empty.")
        elif args.cmd == "export":
            for path in export_reports(repo, cfg.path(cfg.reports_dir)):
                print(path)
        elif args.cmd == "notify-test":
            for n in notifiers:
                try:
                    n.send("NSE monitor test", "Notifications are configured correctly.")
                    print(f"{n.channel}: OK")
                except Exception as exc:
                    print(f"{n.channel}: FAILED - {exc}")
        elif args.cmd == "retry-alerts":
            sent, failed = dispatch_pending(repo, notifiers, cfg.notify.max_attempts)
            print(f"sent {sent}, failed {failed}")
        return 0
    except Exception:
        logging.getLogger("nse_monitor").exception("Command '%s' failed", args.cmd)
        return 1
    finally:
        repo.close()


if __name__ == "__main__":
    sys.exit(main())
